const HEADERS = {
  city: 'Город',
  tariffName: 'Название тарифа',
  priceWithDiscount: 'Цена со скидкой',
  price: 'Цена',
  discountDuration: 'Длительность скидки в мес',
  priceInfo: 'Доп. информация по цене',
  tariffInfo: 'Доп. информация по тарифу',
  discountMark: 'Признак акции',
  speed: 'Скорость мбит/сек',
  routerIncluded: 'WiFi-роутер в комплекте',
  routerForRent: 'WiFi-роутер в аренду',
  routerToBuy: 'WiFi-роутер покупка',
  routerOnInstallment: 'WiFi-роутер в рассрочку',
  tv: 'ТВ Каналов',
  hd: 'HD каналов',
  uhd: 'UHD каналов',
  interactiveTV: 'Интерактивное ТВ каналов',
  tvBoxIncluded: 'ТВ-приставка в комплекте',
  tvBoxForRent: 'ТВ-приставка в аренду',
  tvBoxToBuy: 'ТВ-приставка покупка',
  tvBoxOnInstallment: 'ТВ-приставка в рассрочку',
  mobMinutes: 'Мин',
  mobSms: 'Смс',
  mobGb: 'Гб',
  comment: 'Комментарий к моб. связи',
  priority: 'Приоритет',
};

export default HEADERS;
